config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  resources :users, only: [:new, :create] do
    resources :contacts, only: [:index, :create, :update, :edit]
  end

  namespace :api do
    namespace :v1 do
      resources :months, only: [:update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_many :month_contacts
  has_many :months, through: :month_contacts
  
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/month.rb
class Month < ApplicationRecord
  has_many :month_contacts
  has_many :contacts, through: :month_contacts

  def self.create_all
    months = [
      "Jan", "Feb", "Mar", "Apr", "May", "Jun",
      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
    ]
    months.each do |month|
      create(date: Date.today.to_s, name: month, contact_id: Contact.last.id)
    end
  end

  def self.list
    ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
  end

  def self.days
    num = *(1..31)
    num.map(&:to_s)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :contacts
  has_many :months
end

app/controllers/api/v1/months_controller.rb
class Api::V1::MonthsController < ApplicationController
  # respond_to :json

  # def update
  #   month = Month.find(params[:id])
  #
  #   month.update_attributes(month_params)
  #   month.save
  # end

  def update
    month = Month.find(params[:id])
    if month.update(month_params)
      render json: month
    else
      render 'Invalid Update', status: 400
    end
  end

  private

  def month_params
    params.permit(:method, :date, :meeting, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = current_user.contacts.order(id: :desc)
    @contact = Contact.new
    @months = Month.list
    @days = Month.days
  end

  def create
    @contact = Contact.new(
      user_id: current_user.id,
      first_name: contact_params[:first_name],
      last_name: contact_params[:last_name],
      email: contact_params[:email],
      phone: contact_params[:phone]
    )
    if @contact.save
      Month.create_all
      flash[:success] = "Contact Created!!"
      redirect_to user_contacts_path(current_user)
    else
      redirect_to user_contacts_path(current_user)
      flash[:danger] = @contact.errors.full_messages.join(', ')
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update_attributes(contact_params)
      redirect_to user_contacts_path(current_user)
      flash[:success] = "Contact Updated!"
    else
      flash[:danger] = @contact.errors.full_messages.join(', ')
      render :edit
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :phone)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id

      redirect_to user_contacts_path(current_user)
    else
      flash.now[:danger] = user.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id

      redirect_to user_contacts_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/edit.html.erb
<div class="container">
  <h2>Edit Contact</h2>
  <div class="row">
    <%= form_for [current_user, @contact] do |f| %>
    <%= f.text_field :first_name, placeholder: "First Name" %>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
    <%= f.text_field :email, placeholder: "Email" %>
    <%= f.text_field :phone, placeholder: "Phone" %>
    <%= f.submit "Submit", class: "btn btn-primary btn-sm", method: :put %>
    <% end %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container">
  <div class="row" id="contact-form">
    <h1>Enter Contact</h1>
    <%= form_for [current_user, @contact] do |f| %>
    <%= f.text_field :first_name, placeholder: "First Name" %>
    <%= f.text_field :last_name, placeholder: "Last Name" %><br>
    <%= f.text_field :email, placeholder: "Email" %>
    <%= f.text_field :phone, placeholder: "Phone" %><br>
    <%= f.submit "Submit", class: "btn btn-primary btn-sm contact-submit", method: :post %>
    <% end %>
  </div><br>
  <div class="row">
    <% @months.each do |month| %>
    <button class="btn btn-primary btn-sm" id="<%= month.downcase %>">
      <%= month %>
    </button>
    <% end %>
    <h2>My Network</h2>
    <input id="typed" placeholder="Search Contacts">


    <table id="contactTable" class="jan">
      <thead>
        <tr class="table-row">
          <th>First</th>
          <th>Last</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Date</th>
          <th>Method</th>
          <th>Meeting</th>
          <th>Save</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody id="searchBody">
        <% @contacts.each do |contact| %>
        <tr class="table-row not-contacted" data-month-id="<%= months[0].id.contacts %>">
          <td><%= contact.first_name %></td>
          <td><%= contact.last_name %></td>
          <td><%= contact.email %></td>
          <td><%= number_to_phone(contact.phone) %></td>
          <td>
            <select id="month-date">
              <option><%= contact.months[0].date.to_s[8..9] %></option>
              <% @days.each do |day| %>
                <option><%= day %></option>
              <% end %>
            </select>
          </td>
          <td>
            <select id="month-method">
              <option><%= contact.months[0].method %></option>
              <option>N/A</option>
              <option>Phone</option>
              <option>Email</option>
              <option>Person</option>
            </select>
          </td>
          <td>
            <select id="month-meeting">
              <option><%= contact.months[0].meeting %></option>
              <option>0</option>
              <option>1</option>
              <option>2</option>
            </select>
          </td>
          <td><button type="button" name="button" class="btn btn-primary btn-xs save">Save</button></td>
          <td> <%= link_to "Edit", edit_user_contact_path(current_user, contact), class: "btn btn-primary btn-xs" %> </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <table id="contactTable" class="feb">
      <thead>
        <tr class="table-row">
          <th>First</th>
          <th>Last</th>
          <th>Email</th>
          <th>Phone</th>
          <th id="date">Date</th>
          <th>Method</th>
          <th>Meeting</th>
          <th>Save</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody id="searchBody">
        <% @contacts.each do |contact| %>

        <tr class="table-row contacted" data-month-id="<%= contact.months[1].id %>">
          <td><%= contact.first_name %></td>
          <td><%= contact.last_name %></td>
          <td><%= contact.email %></td>
          <td><%= number_to_phone(contact.phone) %></td>
          <td id="month-date"><%= select_day(Date.today) %></td>
          <td id="month-method">
            <%= select_tag(:method, options_for_select(["N/A", "Phone", "Email", "Person"])) %>
          </td>
          <td id="month-meeting">
            <%= select_tag(:method, options_for_select(["Yes", "No", "N/A"])) %>
          </td>
          <td><button type="button" name="button" class="btn btn-primary btn-xs">Save</button></td>
          <td> <%= link_to "Edit", edit_user_contact_path(current_user, contact), class: "btn btn-primary btn-xs" %> </td>
        </tr>


        <% end %>
      </tbody>
    </table>


  </div>
</div>

app/views/home/show.html.erb
<main class="welcome">
  <h1>Welcome to Network Tracker!</h1>
  <h4>Please Sign Up or Log In</h4>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>NetworkTracker</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <% flash.each do |type, message| %>
  <%= content_tag :div, sanitize(message), class: "alert alert-#{type}" %>
  <% end %>
  <% if current_user %>
  <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-danger logout" %>
  <% else %>
  <%= link_to "Sign Up", new_user_path, class: "btn btn-primary sign-up"   %>
  <%= link_to "Log In", login_path, class: "btn btn-primary log-in" %>
  <% end %>
  <%= yield %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/users/new.html.erb
<div class="container center">
  <h1>Sign Up</h1>
<%= form_for [@user] do |f| %>
<%= f.text_field :email, placeholder: "Email" %>
<br><br>
<%= f.password_field :password, placeholder: "Password" %>
<br><br>
<%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
<br><br>
<%= f.submit "Submit", class: "btn btn-primary btn-sm" %>
<% end %>
</div>